url: zixiang-chen.github.io
baseurl: /a

title: Zixiang Chen
author:
  name: Zixiang Chen
  email: zixiangchen@foxmail.com
  motto: To be pragmatic with passion
copyright: Zixiang Chen © 2020

google_analytics: G-7W4QDBG3WD

include:
  - _pages
header_pages:
  - _pages/cv.md
  - _pages/publications.md
  - _pages/contact.md

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
# - jekyll-pdf-embed
